export const AUTH_USER = 'AUTH_USER'
export const UNAUTH_USER = 'UNAUTH_USER'
export const AUTH_ERROR = 'AUTH_ERROR'
export const FETCH_MESSAGE = 'FETCH_MESSAGE'
export const ADD_COMMENT = 'ADD_COMMENT'
export const SAVE_INFO_USER = 'SAVE_INFO_USER'